trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g npm
      npm install
    displayName: "Install npm packages"

  - script: |
      npm run build
    displayName: "Build project"

  - task: Docker@2
    inputs:
      containerRegistry: "$(dockerRegistryServiceConnection)"
      repository: "$(dockerRegistry)/my-cubejs-app"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: |
        $(Build.BuildId)
